import React from 'react';

import './HomePage.css';

const HomePage = () => {
    return (
        <div className="main-content hugo-home">
            Maecenas placerat ligula mi, vitae semper ex condimentum nec. Nulla at pretium massa. Mauris vitae quam sollicitudin, elementum nibh eget, semper metus. Donec tincidunt, mauris eget posuere lacinia, neque nulla rutrum quam, ac finibus augue quam et sem. Integer fermentum vel lacus id aliquam. Donec nec metus fringilla, feugiat augue id, convallis velit. Aliquam lacinia quam id lectus venenatis, sodales vestibulum turpis tristique. Vivamus laoreet mauris eget turpis dictum sodales. Sed elementum metus ut metus tempus, in maximus mi ullamcorper. Praesent aliquet dignissim purus. Nulla hendrerit, nisi a volutpat sagittis, ex velit volutpat ex, sed congue ligula velit placerat nibh. In in nunc dui. Morbi elementum id risus vitae ornare. Curabitur accumsan feugiat elit. Sed egestas eros ligula, imperdiet porta leo venenatis sit amet. Sed nec ipsum eu ante blandit commodo sit amet facilisis massa. Donec fringilla blandit nibh, eu elementum felis fermentum sed. Suspendisse accumsan felis quis lacus aliquet, a porta nulla tempus. Pellentesque risus nisi, pellentesque id sem eget, scelerisque imperdiet nulla. Nam pharetra, lectus ac aliquam imperdiet, quam turpis vulputate leo, nec interdum neque urna vel lacus. Etiam nisi ligula, sagittis a nibh vel, sollicitudin commodo erat. Nulla varius ullamcorper felis, at suscipit sapien. Aliquam commodo blandit purus, sed iaculis sem viverra ac. Maecenas vestibulum vitae nibh quis mollis. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Maecenas placerat ligula mi, vitae semper ex condimentum nec. Nulla at pretium massa. Mauris vitae quam sollicitudin, elementum nibh eget, semper metus. Donec tincidunt, mauris eget posuere lacinia, neque nulla rutrum quam, ac finibus augue quam et sem. Integer fermentum vel lacus id aliquam. Donec nec metus fringilla, feugiat augue id, convallis velit. Aliquam lacinia quam id lectus venenatis, sodales vestibulum turpis tristique. Vivamus laoreet mauris eget turpis dictum sodales. Sed elementum metus ut metus tempus, in maximus mi ullamcorper. Praesent aliquet dignissim purus. Nulla hendrerit, nisi a volutpat sagittis, ex velit volutpat ex, sed congue ligula velit placerat nibh. In in nunc dui. Morbi elementum id risus vitae ornare. Curabitur accumsan feugiat elit. Sed egestas eros ligula, imperdiet porta leo venenatis sit amet. Sed nec ipsum eu ante blandit commodo sit amet facilisis massa. Donec fringilla blandit nibh, eu elementum felis fermentum sed. Suspendisse accumsan felis quis lacus aliquet, a porta nulla tempus. Pellentesque risus nisi, pellentesque id sem eget, scelerisque imperdiet nulla. Nam pharetra, lectus ac aliquam imperdiet, quam turpis vulputate leo, nec interdum neque urna vel lacus. Etiam nisi ligula, sagittis a nibh vel, sollicitudin commodo erat. Nulla varius ullamcorper felis, at suscipit sapien. Aliquam commodo blandit purus, sed iaculis sem viverra ac. Maecenas vestibulum vitae nibh quis mollis. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Maecenas placerat ligula mi, vitae semper ex condimentum nec. Nulla at pretium massa. Mauris vitae quam sollicitudin, elementum nibh eget, semper metus. Donec tincidunt, mauris eget posuere lacinia, neque nulla rutrum quam, ac finibus augue quam et sem. Integer fermentum vel lacus id aliquam. Donec nec metus fringilla, feugiat augue id, convallis velit. Aliquam lacinia quam id lectus venenatis, sodales vestibulum turpis tristique. Vivamus laoreet mauris eget turpis dictum sodales. Sed elementum metus ut metus tempus, in maximus mi ullamcorper. Praesent aliquet dignissim purus. Nulla hendrerit, nisi a volutpat sagittis, ex velit volutpat ex, sed congue ligula velit placerat nibh. In in nunc dui. Morbi elementum id risus vitae ornare. Curabitur accumsan feugiat elit. Sed egestas eros ligula, imperdiet porta leo venenatis sit amet. Sed nec ipsum eu ante blandit commodo sit amet facilisis massa. Donec fringilla blandit nibh, eu elementum felis fermentum sed. Suspendisse accumsan felis quis lacus aliquet, a porta nulla tempus. Pellentesque risus nisi, pellentesque id sem eget, scelerisque imperdiet nulla. Nam pharetra, lectus ac aliquam imperdiet, quam turpis vulputate leo, nec interdum neque urna vel lacus. Etiam nisi ligula, sagittis a nibh vel, sollicitudin commodo erat. Nulla varius ullamcorper felis, at suscipit sapien. Aliquam commodo blandit purus, sed iaculis sem viverra ac. Maecenas vestibulum vitae nibh quis mollis. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        </div>
    );
};

export default HomePage;