import React from 'react';

import './About.css';

const About = () => {
    return (
        <div className="main-content hugo-about">
            soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon
            soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon
            soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon
            soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon
            soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon
            soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon
            soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon
            soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon
            soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon
            soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon
            soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon
            soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon
            soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon
            soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon soon
        </div>
    );
};

export default About;